//! **The MCP key** — what an editor authenticates to `/mcp` with.
//!
//! Generated by the server on first use rather than configured: nothing to put
//! in a manifest, nothing to paste into the UI. It lives in the encrypted
//! credential store under its own provider, so it survives restarts and is
//! AES-256-GCM at rest like every other secret here.
//!
//! **It is recoverable, not hashed.** The Settings page shows it so the
//! connection snippet can be copied whole, which a hash cannot support. Personal
//! access tokens, which are shown once at creation, will hash instead.
//!
//! **What it is worth.** While the UI is unauthenticated, anyone who can load
//! the page can read the key, so it is a convenience rather than a control. It
//! becomes load-bearing the moment a login sits in front of the UI and `/mcp` is
//! exempted from it — which is the shape of a harness behind an SSO proxy today,
//! and of one with its own accounts later.

use std::collections::BTreeMap;
use std::sync::{Arc, LazyLock};

use axum::http::HeaderMap;
use subtle::ConstantTimeEq;
use tokio::sync::RwLock;

use super::runs_routes::RunsState;

/// Credential provider the key is stored under.
const PROVIDER: &str = "mcp";
const FIELD: &str = "token";

/// Marks the token in logs and lets secret scanners recognise one that has been
/// committed to a repo by mistake — `.mcp.json` is a file people check in.
const PREFIX: &str = "hrn_mcp_";

/// Avoids a database read and a decrypt on every MCP request. Cleared by
/// [`regenerate`], which is the only thing that can invalidate it.
static CACHE: LazyLock<RwLock<Option<String>>> = LazyLock::new(|| RwLock::new(None));

/// 256 bits of randomness from two v4 UUIDs — the same trick
/// [`super::linear_oauth`] uses for its `state` nonce, so `rand` stays out of
/// this crate's dependency list.
fn mint() -> String {
    format!(
        "{PREFIX}{}{}",
        uuid::Uuid::new_v4().simple(),
        uuid::Uuid::new_v4().simple()
    )
}

/// The MCP key, generating and storing one if this install has none.
///
/// `None` when there is nowhere to keep it — no database, or no
/// `HARNESS_SECRET_KEY` to encrypt it with. Callers treat that as "this install
/// cannot use an MCP key" rather than as an error.
pub(crate) async fn ensure(state: &Arc<RunsState>) -> Option<String> {
    if let Some(cached) = CACHE.read().await.clone() {
        return Some(cached);
    }
    // Everything below runs under the write lock so two concurrent first-callers
    // cannot mint two keys and race each other into the store.
    let mut guard = CACHE.write().await;
    if let Some(cached) = guard.clone() {
        return Some(cached);
    }
    let store = state.cred_store().await.ok()?;
    if let Ok(Some(fields)) = store.get(PROVIDER).await {
        if let Some(existing) = fields.get(FIELD).filter(|v| !v.is_empty()) {
            *guard = Some(existing.clone());
            return Some(existing.clone());
        }
    }
    let token = mint();
    let fields = BTreeMap::from([(FIELD.to_string(), token.clone())]);
    if let Err(e) = store.set(PROVIDER, &fields).await {
        tracing::warn!("mcp: could not store the generated key: {e}");
        return None;
    }
    tracing::info!("mcp: generated an MCP key for this install");
    *guard = Some(token.clone());
    Some(token)
}

/// Replace the key. Every editor configured with the old one stops working, so
/// this is a deliberate action — a leak, or handing the install to someone else.
pub(crate) async fn regenerate(state: &Arc<RunsState>) -> Result<String, String> {
    let store = state.cred_store().await?;
    let mut guard = CACHE.write().await;
    let token = mint();
    let fields = BTreeMap::from([(FIELD.to_string(), token.clone())]);
    store
        .set(PROVIDER, &fields)
        .await
        .map_err(|e| e.to_string())?;
    *guard = Some(token.clone());
    tracing::info!("mcp: key regenerated; existing editor configs will stop working");
    Ok(token)
}

/// Warm the key at startup so `/mcp` is guarded from the first request rather
/// than from whenever someone first opens the settings page.
pub(crate) fn spawn_ensure(state: Arc<RunsState>) {
    tokio::spawn(async move {
        if ensure(&state).await.is_none() {
            tracing::warn!(
                "mcp: no MCP key (needs a database and HARNESS_SECRET_KEY) — /mcp falls back \
                 to HARNESS_API_TOKEN, and is unauthenticated when that is unset too"
            );
        }
    });
}

fn bearer(headers: &HeaderMap) -> Option<String> {
    headers
        .get(axum::http::header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|s| s.strip_prefix("Bearer "))
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

fn same(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    a.len() == b.len() && a.ct_eq(b).into()
}

/// Whether a request may use `/mcp`.
///
/// Accepts the MCP key, or the legacy `HARNESS_API_TOKEN` so an editor
/// configured before the key existed keeps working. Falls open only when this
/// install can hold neither — which is exactly what `/mcp` did before this
/// existed, so upgrading never silently locks anyone out of their own harness.
pub(crate) async fn authorized(state: &Arc<RunsState>, headers: &HeaderMap) -> bool {
    // A personal token identifies a person, which is strictly better than the
    // shared key: the run it starts can be attributed to them.
    if super::accounts::user_for_token(state, headers)
        .await
        .is_some()
    {
        return true;
    }
    let key = ensure(state).await;
    let legacy = state.api_token();
    if key.is_none() && legacy.is_none() {
        return true;
    }
    let Some(provided) = bearer(headers) else {
        return false;
    };
    // Both are checked: an install can hold a key *and* still have editors
    // configured with the old shared token.
    key.as_deref().is_some_and(|k| same(&provided, k))
        || legacy.as_deref().is_some_and(|t| same(&provided, t))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_minted_key_is_prefixed_and_unguessable() {
        let a = mint();
        let b = mint();
        assert!(a.starts_with(PREFIX), "{a}");
        assert_ne!(a, b, "each key is its own");
        // Two v4 UUIDs, hyphens stripped: 256 bits of randomness.
        assert_eq!(a.len(), PREFIX.len() + 64);
        assert!(a[PREFIX.len()..].chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn comparison_rejects_near_misses() {
        let key = mint();
        assert!(same(&key, &key.clone()));
        assert!(!same(&key, &key[..key.len() - 1]));
        assert!(!same(&key, &format!("{key}x")));
        assert!(!same(&key, ""));
    }

    #[test]
    fn bearer_reads_only_a_bearer_header() {
        let mut headers = HeaderMap::new();
        assert_eq!(bearer(&headers), None);

        headers.insert(
            axum::http::header::AUTHORIZATION,
            "Bearer abc".parse().unwrap(),
        );
        assert_eq!(bearer(&headers).as_deref(), Some("abc"));

        // Surrounding whitespace is the commonest copy-paste mistake.
        headers.insert(
            axum::http::header::AUTHORIZATION,
            "Bearer  abc  ".parse().unwrap(),
        );
        assert_eq!(bearer(&headers).as_deref(), Some("abc"));

        // Another scheme is not a bearer token.
        headers.insert(
            axum::http::header::AUTHORIZATION,
            "Basic abc".parse().unwrap(),
        );
        assert_eq!(bearer(&headers), None);

        // Present but empty carries no credential.
        headers.insert(
            axum::http::header::AUTHORIZATION,
            "Bearer ".parse().unwrap(),
        );
        assert_eq!(bearer(&headers), None);
    }
}
